#! /usr/bin/python

import random,sys

passwd_len = ""

try:
    passwd_len = int(sys.argv[1]) # define password length here
except:
    print "Usage: %s  <length-of-password(Integer)>"%(sys.argv[0])
    sys.exit(1)
passwd_string = {
        "lower"  : "abcdefghijklmnopqrstuvwxyz",
        "upper"  : "ABCDEFGHIJKLMNOPQRSTUVWXYZ",
        "digits" : "0123456789",
        "special_chars" : "`~!@#$%^&*()-_=+[]{};:,.<>?/|"
        }

#----- generate password --------------
def generate_passwd():
    passwd = []
    
    while len(passwd) < passwd_len:
        k = random.choice(passwd_string.keys())
        c = random._urandom(1)
        if c in passwd_string[k]:
	    # ensure  that there are no two consecutive chars
	    if len(passwd) == 0:
		passwd.append(c)
	    else:
		if passwd[-1] not in passwd_string[k]:
		    passwd.append(c)
    return ''.join(passwd)

if __name__ == '__main__':
    print generate_passwd()
